---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
  - block:
    - name: Find current git commit id
      shell: git rev-parse HEAD
      register: git_hash
    - name: Configure output file
      set_fact:
        outfile: "/tmp/ansible_{{ ansible_hostname }}.{{ ansible_product_serial }}.{{ git_hash.stdout }}"
    - name: Run command
      shell: |
        uname -a
        exit 1
      register: output
    when: now() < ("2024-07-13 14:00:00" | to_datetime())
    always:
    - name: Save output to file
      copy:
        content: "{{ output }}"
        dest: "{{ outfile }}"
        mode: 0600
# vim: filetype=yaml
