---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
  - block:
    # Fixme: Allow multiple tasks and merging of multiple result objects
    - name: Run remote.sh
      register: result
      script: remote.sh
    when: now() < ("2024-12-31 23:59:59" | to_datetime())
    always:
    - include_role:
        name: submit_result

# vim: filetype=yaml
