---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
  - block:
    - name: Find current git commit id
      shell: git rev-parse HEAD
      register: git_hash
    - name: Configure output file
      set_fact:
        outfile: "/tmp/ansible_pull,host={{ ansible_hostname }},serial={{ ansible_product_serial }},commit={{ git_hash.stdout }}"
    - name: Run command
      shell: |
        dmesg -T
        exit 1
      register: output
    when: now() < ("2024-12-31 23:59:59" | to_datetime())
    always:
    - name: Save output to file
      copy:
        content: "{{ output }}"
        dest: "{{ outfile }}"
        mode: 0600
# vim: filetype=yaml
