---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
  - block:
    - name: A few non-invasive apt actions
      apt:
        name:
        - bash
        - openssl
    - name: Some other random thing, but it will fail
      systemd_service:
        name: dummy.service
        enabled: false
    - name: Some thing that might produce interesting output
      shell: iptables -L; ip6tables -L

    rescue:
    - name: Mark play as failed
      set_fact:
        result: 'FAILURE'
  - name: Mark play as success
    set_fact:
      result: 'SUCCESS'

# vim: filetype=yaml
