# Post-execution reporting
- name: Find current git commit id
  shell: git rev-parse HEAD
  register: git_hash
- name: Configure upload filename
  set_fact:
    upload_file: "ansible_pull,host={{ ansible_hostname }},serial={{ ansible_product_serial }},commit={{ git_hash.stdout }}.json"
- name: Upload
  # This is an upload to a public Nextcloud filedrop
  uri:
    url: "{{ upload_url }}/{{ upload_file }}"
    user: "{{ upload_user }}"
    password: ''
    headers:
      X-Requested-With: XMLHttpRequest
    method: PUT
    status_code: 201 # Webdav: 201 Created
    body: "{{ result }}"
    body_format: json

# vim: filetype=yaml
