# Post-execution reporting
- name: Find current git commit id
  shell: git rev-parse HEAD
  register: git_hash
- name: Configure upload filename
  set_fact:
    upload_file: "commit={{ git_hash.stdout }},state={{ result.failed | ternary('FAILURE', 'SUCCESS') }},host={{ ansible_hostname }},serial={{ ansible_product_serial }}.txt"
- name: "Debug: result object"
  debug:
    msg: "{{ result }}"
- name: "Debug: filename"
  debug:
    msg: "{{ upload_file }}"
- name: Upload
  # This is an upload to a public Nextcloud filedrop
  uri:
    url: "{{ upload_url }}/{{ upload_file }}"
    user: "{{ upload_user }}"
    password: ''
    headers:
      X-Requested-With: XMLHttpRequest
    method: PUT
    status_code: 201 # Webdav: 201 Created
    body:
      logfile:
        filename: /tmp/ansible-pull.txt
        mime-type: text/plain
    body_format: raw
# vim: filetype=yaml
